export const ADD_MESSAGES = 'ADD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const LOADING_MESSAGES = 'LOADING_MESSAGES';
export const MESSAGES_FAILED = 'MESSAGES_FAILED';
export const SET_SEEN = 'SET_SEEN';
export const UPDATE_SEEN = 'UPDATE_SEEN'; 

export const LOADING_SEEN = 'LOADING_SEEN';
export const ADD_USERS = 'ADD_USERS';
export const LOADING_USERS = 'LOADING_USERS';
export const USERS_FAILED  = 'USERS_FAILED';

export const SELECTED = 'SELECTED';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SIGNUP_REQUESTED = 'SIGNUP_REQUESTED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';